# Site settings
title: LIUSU
email: susang945@163.com
description: 此博客使用jekyll+github搭建。
url: "https://susang945.github.io" 
twitter_username:
github_username:  susang945

# Build settings
markdown: kramdown
md: kramdown
paginate: 3
gems: [jekyll-paginate]
paginate_path: "/page/:num"
