# Site settings
title: LIUSU
email: susang945@163.com
description: 此博客使用jekyll+github搭建。
url: "https://nicolasjackson.github.io" 
twitter_username:
github_username:  NicolasJackson

# Build settings
markdown: kramdown
paginate: 3
gems: [jekyll-paginate]
paginate_path: "/page/:num"
